version: '3'

services:
  dummy:
    image: mdawid92/test-travis
    container_name: dummy
  db:
    image: postgres
    container_name: db
    volumes:
      - pg:/var/lib/postgresql/data/

volumes:
  pg: